import * as fs from "fs/promises";
import * as path from "path";
import { AnalysisResult, RemoteBrokerResult } from "../types.js";

export async function configRemoteBroker(
  repositoryPath: string,
  configType: string = "both",
  brokerUrl: string = "https://your-pact-broker.example.com",
  analysis: AnalysisResult
): Promise<RemoteBrokerResult> {
  const createdFiles: string[] = [];
  const updatedFiles: string[] = [];
  const configLocations: string[] = [];

  // Create pact.properties if requested
  if (configType === "properties" || configType === "both") {
    const propertiesPath = path.join(
      repositoryPath,
      "src",
      "test",
      "resources",
      "pact.properties"
    );
    await fs.mkdir(path.dirname(propertiesPath), { recursive: true });
    await fs.writeFile(propertiesPath, generatePropertiesFile(brokerUrl), "utf-8");
    createdFiles.push(propertiesPath);
    configLocations.push(propertiesPath);
  }

  // Update Gradle if requested
  if (configType === "gradle" || configType === "both") {
    if (analysis.buildTool === "gradle") {
      const gradleConfigPath = path.join(
        repositoryPath,
        "pact-broker-config.gradle"
      );
      const isKts = await fileExists(path.join(repositoryPath, "build.gradle.kts"));
      
      if (isKts) {
        await fs.writeFile(
          gradleConfigPath.replace(".gradle", ".gradle.kts"),
          generateGradleKtsConfig(brokerUrl),
          "utf-8"
        );
        createdFiles.push(gradleConfigPath.replace(".gradle", ".gradle.kts"));
        configLocations.push(gradleConfigPath.replace(".gradle", ".gradle.kts"));
      } else {
        await fs.writeFile(gradleConfigPath, generateGradleConfig(brokerUrl), "utf-8");
        createdFiles.push(gradleConfigPath);
        configLocations.push(gradleConfigPath);
      }
    }
  }

  // Create CI/CD configuration examples
  const ciConfigPath = path.join(repositoryPath, ".github", "workflows", "pact.yml");
  await fs.mkdir(path.dirname(ciConfigPath), { recursive: true });
  await fs.writeFile(ciConfigPath, generateGitHubActionsConfig(brokerUrl, analysis), "utf-8");
  createdFiles.push(ciConfigPath);
  configLocations.push(ciConfigPath);

  return {
    createdFiles,
    updatedFiles,
    configLocations,
    instructions: [
      "Remote Pact Broker Configuration Created!",
      "",
      "To configure the remote broker, update these placeholders:",
      "",
      "1. pact.properties (for Java/Kotlin projects):",
      "   - Set pactbroker.host to your broker URL",
      "   - Set pactbroker.auth.token to your API token",
      "",
      "2. Environment Variables (recommended for CI/CD):",
      "   - PACT_BROKER_URL: Your Pact Broker URL",
      "   - PACT_BROKER_TOKEN: Your API token (read-write access)",
      "",
      "3. For Pactflow users:",
      "   - Sign up at https://pactflow.io",
      "   - Create an API token in Settings > API Tokens",
      "   - Use the provided broker URL",
      "",
      "4. GitHub Actions workflow created at:",
      `   ${ciConfigPath}`,
      "   - Add PACT_BROKER_URL and PACT_BROKER_TOKEN as repository secrets",
      "",
      "5. Gradle users can include the config file:",
      "   apply from: 'pact-broker-config.gradle'",
    ],
  };
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function generatePropertiesFile(brokerUrl: string): string {
  return `# Pact Broker Configuration
# Generated by pact-contract-mcp
# Author: Sakthikannan Subramanian
#
# Update these values for your remote Pact Broker

# Pact Broker URL
pactbroker.host=${brokerUrl.replace(/^https?:\/\//, "")}
pactbroker.scheme=${brokerUrl.startsWith("https") ? "https" : "http"}
pactbroker.port=${brokerUrl.startsWith("https") ? "443" : "80"}

# Authentication (Token-based - recommended for Pactflow)
pactbroker.auth.token=\${PACT_BROKER_TOKEN}

# Alternative: Basic Authentication
# pactbroker.auth.username=\${PACT_BROKER_USERNAME}
# pactbroker.auth.password=\${PACT_BROKER_PASSWORD}

# Consumer Version Selectors
pactbroker.consumerversionselectors.rawjson=[{"mainBranch": true}, {"deployedOrReleased": true}]

# Publish settings
pactbroker.providerVersion=\${GIT_COMMIT}
pactbroker.providerTags=\${GIT_BRANCH}
pactbroker.enablePending=true
pactbroker.includeWipPactsSince=2024-01-01

# Verification settings
pact.verifier.publishResults=true
`;
}

function generateGradleConfig(brokerUrl: string): string {
  return `// Pact Broker Configuration for Gradle
// Generated by pact-contract-mcp
// Author: Sakthikannan Subramanian
//
// Include this in your build.gradle:
//   apply from: 'pact-broker-config.gradle'

pact {
    broker {
        // Remote Pact Broker URL
        pactBrokerUrl = System.getenv('PACT_BROKER_URL') ?: '${brokerUrl}'
        
        // Token-based authentication (recommended)
        pactBrokerToken = System.getenv('PACT_BROKER_TOKEN') ?: ''
        
        // Alternative: Basic authentication
        // pactBrokerUsername = System.getenv('PACT_BROKER_USERNAME') ?: ''
        // pactBrokerPassword = System.getenv('PACT_BROKER_PASSWORD') ?: ''
    }
    
    serviceProviders {
        // Configure your provider here
        // 'your-provider-name' {
        //     protocol = 'http'
        //     host = 'localhost'
        //     port = 8080
        //     path = '/'
        //     
        //     fromPactBroker {
        //         selectors = latestTags('main', 'production')
        //         enablePending = true
        //         providerTags = System.getenv('GIT_BRANCH')
        //     }
        // }
    }
    
    publish {
        pactDirectory = "\${buildDir}/pacts"
        consumerVersion = System.getenv('GIT_COMMIT') ?: project.version
        tags = [System.getenv('GIT_BRANCH') ?: 'local']
    }
}

// Provider verification task
task verifyPacts(type: Test) {
    description = 'Verify provider contracts from Pact Broker'
    group = 'pact'
    
    useJUnitPlatform()
    include '**/*ProviderPactTest*'
    
    systemProperty 'pact.verifier.publishResults', 'true'
    systemProperty 'pact.provider.version', System.getenv('GIT_COMMIT') ?: project.version
    systemProperty 'pact.provider.tag', System.getenv('GIT_BRANCH') ?: 'local'
}

// Can-I-Deploy check
task canIDeploy {
    description = 'Check if this version can be deployed'
    group = 'pact'
    
    doLast {
        def brokerUrl = System.getenv('PACT_BROKER_URL') ?: '${brokerUrl}'
        def token = System.getenv('PACT_BROKER_TOKEN') ?: ''
        def pacticipant = project.name
        def version = System.getenv('GIT_COMMIT') ?: project.version
        def environment = System.getenv('DEPLOY_ENV') ?: 'production'
        
        exec {
            commandLine 'pact-broker', 'can-i-deploy',
                '--pacticipant', pacticipant,
                '--version', version,
                '--to-environment', environment,
                '--broker-base-url', brokerUrl,
                '--broker-token', token
        }
    }
}
`;
}

function generateGradleKtsConfig(brokerUrl: string): string {
  return `// Pact Broker Configuration for Gradle Kotlin DSL
// Generated by pact-contract-mcp
// Author: Sakthikannan Subramanian
//
// Include this in your build.gradle.kts:
//   apply(from = "pact-broker-config.gradle.kts")

pact {
    broker {
        // Remote Pact Broker URL
        pactBrokerUrl.set(System.getenv("PACT_BROKER_URL") ?: "${brokerUrl}")
        
        // Token-based authentication (recommended)
        pactBrokerToken.set(System.getenv("PACT_BROKER_TOKEN") ?: "")
        
        // Alternative: Basic authentication
        // pactBrokerUsername.set(System.getenv("PACT_BROKER_USERNAME") ?: "")
        // pactBrokerPassword.set(System.getenv("PACT_BROKER_PASSWORD") ?: "")
    }
    
    publish {
        pactDirectory.set("\${buildDir}/pacts")
        consumerVersion.set(System.getenv("GIT_COMMIT") ?: project.version.toString())
        tags.set(listOf(System.getenv("GIT_BRANCH") ?: "local"))
    }
}

// Provider verification task
tasks.register<Test>("verifyPacts") {
    description = "Verify provider contracts from Pact Broker"
    group = "pact"
    
    useJUnitPlatform()
    include("**/*ProviderPactTest*")
    
    systemProperty("pact.verifier.publishResults", "true")
    systemProperty("pact.provider.version", System.getenv("GIT_COMMIT") ?: project.version)
    systemProperty("pact.provider.tag", System.getenv("GIT_BRANCH") ?: "local")
}

// Can-I-Deploy check
tasks.register("canIDeploy") {
    description = "Check if this version can be deployed"
    group = "pact"
    
    doLast {
        val brokerUrl = System.getenv("PACT_BROKER_URL") ?: "${brokerUrl}"
        val token = System.getenv("PACT_BROKER_TOKEN") ?: ""
        val pacticipant = project.name
        val version = System.getenv("GIT_COMMIT") ?: project.version.toString()
        val environment = System.getenv("DEPLOY_ENV") ?: "production"
        
        exec {
            commandLine(
                "pact-broker", "can-i-deploy",
                "--pacticipant", pacticipant,
                "--version", version,
                "--to-environment", environment,
                "--broker-base-url", brokerUrl,
                "--broker-token", token
            )
        }
    }
}
`;
}

function generateGitHubActionsConfig(
  brokerUrl: string,
  analysis: AnalysisResult
): string {
  const buildCommand =
    analysis.buildTool === "gradle"
      ? "./gradlew runContractTests"
      : "mvn test -Dtest=*PactTest";

  const publishCommand =
    analysis.buildTool === "gradle"
      ? "./gradlew pactPublish"
      : "mvn pact:publish";

  return `# Pact Contract Testing Workflow
# Generated by pact-contract-mcp
# Author: Sakthikannan Subramanian
#
# This workflow runs Pact contract tests and publishes results to the broker

name: Pact Contract Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  PACT_BROKER_URL: \${{ secrets.PACT_BROKER_URL }}
  PACT_BROKER_TOKEN: \${{ secrets.PACT_BROKER_TOKEN }}

jobs:
  consumer-contract-tests:
    name: Consumer Contract Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.m2/repository
          key: \${{ runner.os }}-deps-\${{ hashFiles('**/*.gradle*', '**/pom.xml') }}
          restore-keys: |
            \${{ runner.os }}-deps-
            
      - name: Run Consumer Pact Tests
        run: ${buildCommand}
        env:
          GIT_COMMIT: \${{ github.sha }}
          GIT_BRANCH: \${{ github.ref_name }}
          
      - name: Publish Pact Contracts
        if: github.event_name == 'push'
        run: ${publishCommand}
        env:
          GIT_COMMIT: \${{ github.sha }}
          GIT_BRANCH: \${{ github.ref_name }}

  provider-contract-tests:
    name: Provider Contract Tests
    runs-on: ubuntu-latest
    needs: consumer-contract-tests
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.m2/repository
          key: \${{ runner.os }}-deps-\${{ hashFiles('**/*.gradle*', '**/pom.xml') }}
          restore-keys: |
            \${{ runner.os }}-deps-
            
      - name: Verify Provider Contracts
        run: ${analysis.buildTool === "gradle" ? "./gradlew verifyPacts" : "mvn pact:verify"}
        env:
          GIT_COMMIT: \${{ github.sha }}
          GIT_BRANCH: \${{ github.ref_name }}

  can-i-deploy:
    name: Can I Deploy?
    runs-on: ubuntu-latest
    needs: [consumer-contract-tests, provider-contract-tests]
    if: github.event_name == 'push'
    
    steps:
      - name: Check deployment safety
        uses: pactflow/actions/can-i-deploy@v1
        with:
          broker_url: \${{ secrets.PACT_BROKER_URL }}
          broker_token: \${{ secrets.PACT_BROKER_TOKEN }}
          application_name: \${{ github.event.repository.name }}
          version: \${{ github.sha }}
          to_environment: production
          retry_while_unknown: 12
          retry_interval: 10
`;
}
