import * as fs from "fs/promises";
import * as path from "path";
import { LocalBrokerResult } from "../types.js";

export async function setupLocalBroker(
  repositoryPath: string,
  brokerPort: number = 9292,
  postgresPort: number = 5432
): Promise<LocalBrokerResult> {
  const dockerComposeContent = generateDockerCompose(brokerPort, postgresPort);
  const dockerComposePath = path.join(repositoryPath, "docker-compose.pact.yml");

  await fs.writeFile(dockerComposePath, dockerComposeContent, "utf-8");

  // Also create a .env.pact file for environment variables
  const envContent = generateEnvFile(brokerPort);
  const envPath = path.join(repositoryPath, ".env.pact");
  await fs.writeFile(envPath, envContent, "utf-8");

  return {
    dockerComposeFile: dockerComposePath,
    startCommand: `docker-compose -f docker-compose.pact.yml up -d`,
    stopCommand: `docker-compose -f docker-compose.pact.yml down`,
    brokerUrl: `http://localhost:${brokerPort}`,
    instructions: [
      `1. Start the Pact Broker: docker-compose -f docker-compose.pact.yml up -d`,
      `2. Access the Pact Broker UI at: http://localhost:${brokerPort}`,
      `3. Default credentials: pact_user / pact_password`,
      `4. View published contracts and verification results in the UI`,
      `5. Stop the broker: docker-compose -f docker-compose.pact.yml down`,
      `6. To persist data, the PostgreSQL data is stored in a Docker volume`,
    ],
  };
}

function generateDockerCompose(
  brokerPort: number,
  postgresPort: number
): string {
  return `# Pact Broker Docker Compose Configuration
# Generated by pact-contract-mcp
# Author: Sakthikannan Subramanian
#
# Usage:
#   Start: docker-compose -f docker-compose.pact.yml up -d
#   Stop:  docker-compose -f docker-compose.pact.yml down
#   Logs:  docker-compose -f docker-compose.pact.yml logs -f

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pact-postgres
    environment:
      POSTGRES_USER: pact_user
      POSTGRES_PASSWORD: pact_password
      POSTGRES_DB: pact_broker
    ports:
      - "${postgresPort}:5432"
    volumes:
      - pact-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pact_user -d pact_broker"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pact-network

  pact-broker:
    image: pactfoundation/pact-broker:latest
    container_name: pact-broker
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PACT_BROKER_DATABASE_URL: postgres://pact_user:pact_password@postgres/pact_broker
      PACT_BROKER_DATABASE_USERNAME: pact_user
      PACT_BROKER_DATABASE_PASSWORD: pact_password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pact_broker
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: none
      # Basic auth (optional - remove for open access)
      PACT_BROKER_BASIC_AUTH_USERNAME: pact_user
      PACT_BROKER_BASIC_AUTH_PASSWORD: pact_password
      PACT_BROKER_ALLOW_PUBLIC_READ: "true"
      # Webhook configuration
      PACT_BROKER_WEBHOOK_HOST_WHITELIST: ".*"
      # Base URL for links
      PACT_BROKER_BASE_URL: http://localhost:${brokerPort}
    ports:
      - "${brokerPort}:9292"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9292/diagnostic/status/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pact-network

volumes:
  pact-postgres-data:
    driver: local

networks:
  pact-network:
    driver: bridge
`;
}

function generateEnvFile(brokerPort: number): string {
  return `# Pact Broker Environment Variables
# Generated by pact-contract-mcp
# Author: Sakthikannan Subramanian
#
# Use these in your application/build configuration

# Local Pact Broker URL
PACT_BROKER_URL=http://localhost:${brokerPort}

# Local Pact Broker Credentials (if basic auth is enabled)
PACT_BROKER_USERNAME=pact_user
PACT_BROKER_PASSWORD=pact_password

# For token-based auth (when using Pactflow or similar)
# PACT_BROKER_TOKEN=your-read-write-token

# Verification settings
PACT_PUBLISH_RESULTS=true
PACT_PROVIDER_VERSION=\${VERSION:-local}
`;
}
